# Generated by Django 3.0.8 on 2020-08-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raila',
            name='comment',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='raila',
            table='thugs_raila',
        ),
    ]
