# Generated by Django 3.0.8 on 2020-08-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thugs', '0002_auto_20200824_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raila',
            name='comment',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
