# Generated by Django 3.0.8 on 2020-08-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thugs', '0003_auto_20200824_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raila',
            name='commision',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
