# Generated by Django 3.0.8 on 2020-08-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thugs', '0004_auto_20200824_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raila',
            name='betrs',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
