# Generated by Django 3.0.8 on 2020-08-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thugs', '0006_auto_20200824_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raila',
            name='commision',
            field=models.CharField(max_length=20),
        ),
    ]
