# Generated by Django 3.0.8 on 2020-08-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thugs', '0007_auto_20200824_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raila',
            name='comment',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
    ]
