# Generated by Django 3.0.8 on 2020-08-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thugs', '0008_auto_20200824_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raila',
            name='comment',
            field=models.CharField(max_length=20),
        ),
    ]
