# Generated by Django 3.0.8 on 2020-08-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thugs', '0009_auto_20200824_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raila',
            name='comment',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
