# Generated by Django 3.0.8 on 2020-08-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thugs', '0012_auto_20200826_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminbet',
        ),
    ]
