# Generated by Django 3.0.8 on 2020-08-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thugs', '0014_adminbet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminbet',
        ),
    ]
